artifact_location: file:///home/claudio/Scrivania/ml-ops-challenge/src/mlchallengeruns/0
creation_time: 1753894036835
experiment_id: '0'
last_update_time: 1753894036835
lifecycle_stage: active
name: Default
