apiVersion: apps/v1
kind: Deployment
metadata:
  # anche qui fix
  name: "{{ .Release.Name }}-mlops-api"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
        - name: mlops-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80