apiVersion: v1
kind: Service
metadata:
  # fix
  name: "{{ .Release.Name }}-mlops-api"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: mlops-api