artifact_location: file:///home/claudio/Scrivania/ml-ops-challenge/src/mlchallengeruns/256807186608152322
creation_time: 1753894036841
experiment_id: '256807186608152322'
last_update_time: 1753894036841
lifecycle_stage: active
name: Comparazione Modello Iris
